### ISSUE TITLE
instance/tmp/webapps/metrics.war/webapp/,UNAVAILABLE,@Connector-0}{/var/lib/artemis-instance/web/metrics.war}

### ISSUE THREAD

**Issue by svanschalkwyk** [rh-messaging/artemis-prometheus-metrics-plugin#31]
Injecting this into Docker, alongside the opentelemetry-javaagent.jar:
Using image  apache/activemq-artemis:2.33.0 and injecting the javaagent.jar in the dockerfile. 

`  activemq-service:
    build:
      context: ../../
      dockerfile: ./ci/Docker-Images-Local/dockerfile.artemis
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin
      ANONYMOUS_LOGIN: "false"
      OTEL_SERVICE_NAME: activemq-service 
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_JAVAAGENT_DEBUG: false
      JAVA_AGENT: https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v2.4.0/opentelemetry-javaagent.jar
    volumes: 
      - ./artemis/config:/var/lib/artemis-instance/etc-override
      - ./artemis/lib:/var/lib/artemis-instance/lib
      - ./artemis/web:/var/lib/artemis-instance/web
    ports:
      - 8161:8161
      - 9404:9404
      - 1099:1099
      - 61616:61616
`
The metrics.war file is in /var/lib/artemis-instance/web, the jar is in the /var/lib/artemis-instance/lib, and the bootstrap.xml and broker.xml are configured. 

Receiving this log output: 

`2024-06-04 22:02:31,673 WARN  [org.eclipse.jetty.webapp.WebAppContext] Failed startup of context o.e.j.w.WebAppContext@39595a8{/metrics,file:///var/lib/artemis-instance/tmp/webapps/metrics.war/webapp/,UNAVAILABLE,@Connector-0}{/var/lib/artemis-instance/web/metrics.war}
java.lang.NoClassDefFoundError: jakarta/servlet/http/HttpServlet
        at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.base/java.lang.ClassLoader.defineClass(Unknown Source) ~[?:?]
        at java.base/java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:?]
        at java.base/java.net.URLClassLoader.defineClass(Unknown Source) ~[?:?]
        at java.base/java.net.URLClassLoader$1.run(Unknown Source) ~[?:?]
        at java.base/java.net.URLClassLoader$1.run(Unknown Source) ~[?:?]
        at java.base/java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
        at java.base/java.net.URLClassLoader.findClass(Unknown Source) ~[?:?]
        at org.eclipse.jetty.webapp.WebAppClassLoader.foundClass(WebAppClassLoader.java:594) ~[jetty-webapp-10.0.20.jar:10.0.20]
        at org.eclipse.jetty.webapp.WebAppClassLoader.loadAsResource(WebAppClassLoader.java:567) ~[jetty-webapp-10.0.20.jar:10.0.20]
        at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:502) ~[jetty-webapp-10.0.20.jar:10.0.20]
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at org.eclipse.jetty.util.Loader.loadClass(Loader.java:59) ~[jetty-util-10.0.20.jar:10.0.20]
        at org.eclipse.jetty.servlet.BaseHolder.doStart(BaseHol`
Any ideas how to solve this?

**Comment by brusdev** [comment]
@svanschalkwyk artemis-prometheus-metrics-plugin 3.x is for future ActiveMQArtemis versions. You can use artemis-prometheus-metrics-plugin 2.1.0 for ActiveMQArtemis 2.33.0, see #29 for further details

**Comment by svanschalkwyk** [comment]
Thank you @brusdev . Trying now.
